version: '3'

services:

  nginx:
    build: .build/docker/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./.build/docker/nginx/nginx/:/etc/nginx/
    depends_on:
      - php
    networks:
      - internal

  php:
    build: .build/docker/php
    volumes:
      - ./:/app
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.180.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - postgres
    networks:
      - internal

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: service
      POSTGRES_USER: service
      POSTGRES_DB: service
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.180.0/29
